uses: appleboy/ssh-action@master
with:
  host: ${{ inputs.host }}
  username: ${{ inputs.username }}
  key: ${{ inputs.key }}
  script: |
    cd ~/IMS-Corp
    git pull origin dev
    docker compose build
    docker compose up -d
