name: 'SSH and Deploy'
description: 'Connects to a remote server via SSH and deploys the code'
inputs:
  host:
    description: 'SSH host'
    required: true
  username:
    description: 'SSH username'
    required: true
  key:
    description: 'SSH private key'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
