name: 'SSH and Deploy'
description: 'SSH into a server and deploy the application'
inputs:
  host:
    description: 'SSH Host'
    required: true
  username:
    description: 'SSH Username'
    required: true
  key:
    description: 'SSH Private Key'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
