name: 'Send Notification'
description: 'Send an email notification'
inputs:
  server_address:
    description: 'SMTP server address'
    required: true
  server_port:
    description: 'SMTP server port'
    required: true
  username:
    description: 'SMTP server username'
    required: true
  password:
    description: 'SMTP server password'
    required: true
  to:
    description: 'Recipient email address'
    required: true
  from:
    description: 'Sender email address'
    required: true
  subject:
    description: 'Email subject'
    required: true
  body:
    description: 'Email body'
    required: true
runs:
  using: 'node16'
  main: 'send_notification.js'
