name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: github
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/deployment
          git pull origin master
          docker-compose build
          docker-compose up -d
