name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat 'The runner can come into the server' > ~/ami_pouchechi.txt
            cd ~/IMS-Corp
            git pull origin dev
            docker compose build --no-cache
            docker compose up -d

      - name: Send Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.MAIL_SERVER_PORT }}
          username: ${{ secrets.MAIL_SERVER_UID }}
          password: ${{ secrets.MAIL_SERVER_PASS }}
          subject: "IMS-Corp Deployed"
          body: "IMS-Corp has been deployed successfully"
          to: "bhunia.sanchayan@gmail.com"
          from: ${{ secrets.username }}
