name: Deploy on Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare Email
        id: prepare_email
        run: |
          deployment_time="$(date)"
          # Modify this path to point to the correct location of your HTML file
          html_file_path="./templates/notify_deployment-staging.html"
          # Check if the file exists and read it
          if [ -f "$html_file_path" ]; then
            content=$(cat "$html_file_path")
            # Replace the placeholders here as needed
            # ...
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            echo "::set-output name=content::$content"
          else
            echo "HTML file not found at $html_file_path"
            exit 1
          fi

      # Other steps for SSH and Deploy and Send Notification...
