name: Deploy on Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -i ~/.ssh/id_rsa <<EOF
          cd ~/IMS-Corp
          git pull origin dev
          docker compose build --no-cache
          docker compose up -d
          exit
          EOF

      - name: Prepare Email
        id: prepare_email
        run: |
          deployment_time="$(date)"
          branch_name="${GITHUB_REF##*/}"
          commit_message="$(git log --format=%B -n 1 ${{ github.sha }})"
          author_name="$(git log --format='%an' -n 1)"
          author_email="$(git log --format='%ae' -n 1)"
          files_changed="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
          content=$(sed -e "s/{DEPLOYMENT_TIME}/$deployment_time/g" \
                       -e "s/{BRANCH_NAME}/$branch_name/g" \
                       -e "s/{COMMIT_MESSAGE}/$commit_message/g" \
                       -e "s/{AUTHOR_NAME}/$author_name/g" \
                       -e "s/{AUTHOR_EMAIL}/$author_email/g" \
                       -e "s/{FILES_CHANGED}/$files_changed/g" ./templates/email/notify_deployment-staging.html)
          echo "::set-output name=content::$content"

      - name: Send Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.MAIL_SERVER_PORT }}
          username: ${{ secrets.MAIL_SERVER_UID }}
          password: ${{ secrets.MAIL_SERVER_PASS }}
          subject: "IMS-Corp Deployed"
          body: ${{ steps.prepare_email.outputs.content }}
          from: ${{ secrets.MAIL_SERVER_UID }}
          to: "bhunia.sanchayan@gmail.com"
