name: Deploy on Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -i ~/.ssh/id_rsa <<EOF
          cd ~/IMS-Corp
          git pull origin dev
          docker compose build --no-cache
          docker compose up -d
          exit
          EOF
        
      - name: Send Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.MAIL_SERVER_PORT }}
          secure: ${{ secrets.MAIL_SERVER_SECURE }}
          username: ${{ secrets.MAIL_SERVER_UID }}
          password: ${{ secrets.MAIL_SERVER_PASS }}
          subject: "IMS-Corp Deployed"
          body: "IMS-Corp has been deployed successfully"
          from: ${{ secrets.MAIL_SERVER_UID }}
          to: "bhunia.sanchayan@gmail.com"