name: Deploy on Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -i ~/.ssh/id_rsa <<EOF
          cd ~/IMS-Corp
          git pull origin dev
          docker compose build
          docker compose up -d
          exit
          EOF

      - name: Prepare Email
        id: prepare_email
        run: |
          deployment_time="$(date)"
          git fetch --unshallow
          last_commit_hash=$(git rev-parse HEAD)
          author_name=$(git log -1 --format='%an')
          author_email=$(git log -1 --format='%ae')
          files_changed=$(git diff-tree --no-commit-id --name-only -r $last_commit_hash)
          template_path="./templates/email/notify_deployment-staging.html"
          content=$(cat $template_path)
          content=${content//PLACEHOLDER_DEPLOYMENT_TIME/$deployment_time}
          content=${content//PLACEHOLDER_AUTHOR_NAME/$author_name}
          content=${content//PLACEHOLDER_AUTHOR_EMAIL/$author_email}
          content=${content//PLACEHOLDER_FILES_CHANGED/$files_changed}
          
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -i ~/.ssh/id_rsa <<EOF
          echo pwd
          echo "$content" > ~/IMS-Corp/emails/notify_deployment-staging.html
          exit
          EOF
        
