name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Gather Information
        id: gather_info
        run: |
          echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log --format='%an <%ae>' -n 1 ${{ github.sha }})" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git log --format='%ad' --date=format:'%Y-%m-%d %H:%M:%S' -n 1 ${{ github.sha }})" >> $GITHUB_ENV

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/IMS-Corp
            git pull origin dev
            docker compose build
            docker compose up -d

      - name: Send Notification
        run: |
          echo "Deployment Notification" > email_subject.txt
          echo "Deployment Details:" > email_body.txt
          echo "Branch: $BRANCH_NAME" >> email_body.txt
          echo "Commit Message: $COMMIT_MESSAGE" >> email_body.txt
          echo "Author: $COMMIT_AUTHOR" >> email_body.txt
          echo "Date: $COMMIT_DATE" >> email_body.txt
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.brahmware.com
          server_port: 465
          username: ${{ secrets.MAIL_SERVER_UID }}
          password: ${{ secrets.MAIL_SERVER_PASS }}
          subject: email_subject.txt
          to: "bhunia.sanchayan@gmail.com"
          from: ${{ secrets.MAIL_SERVER_UID }}
          body: email_body.txt
